version: '3'

services:
    # myapp-nginx: 
    #   build: .
    #   container_name: myapp-nginx
    #   restart: always
    #   ports:
    #     - 8080:80
    #   volumes:
    #     - ./html:/usr/share/nginx/html

    # mysql:
    #   image: mysql:8
    #   container_name: mysql
    #   restart: always
    #   environment:
    #     MYSQL_ROOT_PASSWORD: root
    #     MYSQL_DATABASE: fullcycle
    #   ports:
    #     - 3306:3306
    #   volumes:
    #     - ./mysql:/var/lib/mysql

    # rabbitmq: 
    #   image: rabbitmq:3-management
    #   container_name: rabbitmq
    #   restart: always
    #   ports:
    #     - 5672:5672
    #     - 15672:15672

    mssql:
      image: mcr.microsoft.com/mssql/server:2019-latest
      user: root
      ports:
        - 1500:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Teste@2023
      volumes:
          - ./mssql:/var/opt/mssql/data
        # - ./mssql/data:/var/opt/mssql/data
        # - ./mssql/log:/var/opt/mssql/log
        # - ./mssql/secrets:/var/opt/mssql/secrets